name: Java CI with Gradle

on:
  workflow_dispatch:
    inputs:
      project:
        description: 'Project name'
        required: true
        default: 'all'
        options:
          - all
          - app

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - if: ${{ github.event.inputs.project == 'all' }}
      name: Execute Gradle build
      run: ./gradlew build

    - if: ${{ github.event.inputs.project != 'all' }}
      name: Execute Gradle build
      run: ./gradlew :${{ github.event.inputs.project }}:build
      
    - uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: build/libs/
